config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pets#index"

  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
# frozen_string_literal: true

class Pet < ApplicationRecord
  validates :name, :breed, :url, :description, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def render_errors(turbo_stream, errors)
    turbo_stream.replace('form-errors', partial: 'layouts/shared/errors', locals: { errors: errors })
  end

  def render_success(turbo_stream, object, action)
    turbo_stream.replace('form-success', partial: 'layouts/shared/success', locals: { object: object, action: action })
  end
end

app/controllers/pets_controller.rb
# frozen_string_literal: true

# Endpoints for pets
class PetsController < ApplicationController
  before_action :set_pet, except: %i[index new create]

  def index
    @pets = Pets::List.call
  end

  def new
    @pet = Pet.new
  end

  def edit
  end

  def create
    create_service = Pets::Create.call(params: pet_params)

    @pet = create_service.result

    respond_to do |format|
      if create_service.success?
        format.html { redirect_to pets_path }
        format.turbo_stream do
          render turbo_stream: render_success(turbo_stream, 'Pet', 'created')
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream do
          render turbo_stream: render_errors(turbo_stream, create_service.errors)
        end
      end
    end
  end

  def update
    update_service = Pets::Update.call(pet: @pet, params: pet_params)

    respond_to do |format|
      if update_service.success?
        format.html { redirect_to pets_path }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.turbo_stream do
          render turbo_stream: render_errors(turbo_stream, update_service.errors)
        end
      end
    end
  end

  def destroy
    @pet.delete

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("pet_#{@pet.id}") }
    end
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :breed, :url, :description)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# General Helpers
module ApplicationHelper
  def page_header(title:)
    content_tag(:div, class: 'header mt-2') do
      content_tag(:h1, title)
    end
  end

  def errors_for(object, field)
    content_tag(:div, object.errors[field].join(', '), class: 'text-danger') if object.errors[field].present?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetCatalogHotwire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render 'layouts/shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_errors.html.erb
<% if errors && errors&.any? %>
  <div class="alert alert-danger">
    <ul>
      <% errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/shared/_header.html.erb
<nav class="navbar" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <h1><%= link_to 'PetCatalog', root_path, class: "navbar-brand" %></h1>
  </div>
</nav>

app/views/layouts/shared/_modal.html.erb
<div class="modal fade" id="<%= modal_id %>" tabindex="-1" aria-labelledby="<%= modal_id %>-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= modal_title %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
      </div>
      <div class="modal-body">
        <%= yield %>
      </div>
      <div class="modal-footer">
        <%= modal_footer %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/shared/_success.html.erb
<div id="success_message" class="alert alert-info" role="alert">
  <p><%= "#{object} was #{action} successfully." %></p>
</div>

app/views/pets/_form.html.erb
<div class="mt-4">
  <div class="card">
    <div class="card-body">
      <%= simple_form_for @pet, html: { class: "form" } do |f| %>
        <div id="form-errors">
          <%= render 'layouts/shared/errors', errors: nil %>
        </div>

        <div class="row">
          <div class="col">
            <%= f.input :name, id: "name", class: "form-control form-control-lg" %>
            <%= f.error :name %>
          </div>

          <div class="col">
            <%= f.input :breed, id: "breed", class: "form-control" %>
            <%= f.error :breed %>
          </div>

          <div class="col">
            <%= f.input :url, id: "url", class: "form-control form-control-lg" %>
            <%= f.error :url %>
          </div>
        </div>

        <div class="row">
          <div class="col">
            <%= f.input :description, as: :text, id: "description", class: "form-control form-control-lg" %>
            <%= f.error :description %>
          </div>
        </div>

        <%= f.button :submit, class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/pets/_pet.html.erb
<div class="card" style="width: 18rem;">
  <img src="<%= pet.url %>" class="card-img-top" alt="<%= pet.name %>" width="354" height="222" >
  <div class="card-body">
    <h5 class="card-title"><%= pet.name %></h5>
    <p class="card-text"><small class="text-body-secondary"><%= pet.breed %></small></p>
    <p class="card-text"><%= pet.description %></p>
    <div class="container text-center">
      <div class="row">
        <div class="col-6 d-grid">
          <%= link_to 'Edit', edit_pet_path(pet), class: 'btn btn-primary btn-lg btn-block', data: { "turbo-prefetch": false, turbo_frame: "list_pets" } %>
        </div>
        <div class="col-6 d-grid">
          <%= link_to 'Delete', pet_path(pet), class: 'btn btn-danger btn-lg btn-block', data: { turbo_confirm: 'Are you sure?', method: :delete, turbo_method: :delete } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pets/edit.html.erb
<div class="container">
  <%= turbo_frame_tag "list_pets" do %>
    <%= page_header(title: 'Edit Pet') %>

    <%= render partial: 'form', pet: @pet %>
  <% end %>
</div>

app/views/pets/index.html.erb
<div class="container">
  <%= turbo_frame_tag "list_pets" do %>
    <%= page_header(title: 'Pets') %>

    <div class="row me-2 mb-4">
      <div class="col text-end">
        <%= link_to "New pet", new_pet_path, class: "btn btn-primary", data: { turbo_prefetch: false, turbo_frame: "list_pets" } %>
      </div>
    </div>

    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4">
      <% @pets.each do |pet| %>
        <%= turbo_frame_tag "pet_#{pet.id}" do %>
          <%= render partial: 'pet', locals: { pet: pet } %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/pets/new.html.erb
<div class="container">
  <%= turbo_frame_tag "list_pets" do %>
    <%= page_header(title: 'New Pet') %>

    <%= render partial: 'form', pet: @pet %>
  <% end %>
</div>